version: '2'
services:
    quanlikho-app:
        image: quanlikho
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://quanlikho-postgresql:5432/quanlikho
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    quanlikho-postgresql:
        extends:
            file: postgresql.yml
            service: quanlikho-postgresql
